#coding=utf8
from AftersaleGet import *
from AppstoreSubscribeGet import *
from AreasGet import *
from FavoriteAdd import *
from FavoriteSearch import *
from FenxiaoCooperationUpdate import *
from FenxiaoDiscountAdd import *
from FenxiaoDiscountsGet import *
from FenxiaoDiscountUpdate import *
from FenxiaoDistributorsGet import *
from FenxiaoGradesGet import *
from FenxiaoOrdersGet import *
from FenxiaoProductAdd import *
from FenxiaoProductcatsGet import *
from FenxiaoProductsGet import *
from FenxiaoProductUpdate import *
from GuarantyfundsGet import *
from HuabaoChannelGet import *
from HuabaoChannelsGet import *
from HuabaoPosterGet import *
from HuabaoPosterGoodsinfoGet import *
from HuabaoPostersGet import *
from HuabaoSpecialpostersGet import *
from IncrementAppSubscribe import *
from IncrementAuthorizemessagesGet import *
from IncrementItemsGet import *
from IncrementRefundsGet import *
from IncrementSubscribemessageGet import *
from IncrementTradesGet import *
from ItemAdd import *
from ItemcatsAuthorizeGet import *
from ItemcatsGet import *
from ItemDelete import *
from ItemGet import *
from ItemImgDelete import *
from ItemImgUpload import *
from ItemPropimgDelete import *
from ItemPropimgUpload import *
from ItempropsGet import *
from ItempropvaluesGet import *
from ItemQuantityUpdate import *
from ItemRecommendAdd import *
from ItemRecommendDelete import *
from ItemsCustomGet import *
from ItemsGet import *
from ItemsInventoryGet import *
from ItemSkuAdd import *
from ItemSkuDelete import *
from ItemSkuGet import *
from ItemSkusGet import *
from ItemSkuUpdate import *
from ItemsListGet import *
from ItemsOnsaleGet import *
from ItemsSearch import *
from ItemUpdate import *
from ItemUpdateDelisting import *
from ItemUpdateListing import *
from KfcKeywordSearch import *
from LogisticsAddressAdd import *
from LogisticsAddressModify import *
from LogisticsAddressRemove import *
from LogisticsAddressSearch import *
from LogisticsCompaniesGet import *
from LogisticsDummySend import *
from LogisticsOfflineSend import *
from LogisticsOnlineCancel import *
from LogisticsOnlineConfirm import *
from LogisticsOnlineSend import *
from LogisticsOrdersDetailGet import *
from LogisticsOrdersGet import *
from LogisticsPartnersGet import *
from LogisticsTraceSearch import *
from PictureCategoryGet import *
from PictureDelete import *
from PictureGet import *
from PictureUpload import *
from PostageAdd import *
from PostageDelete import *
from PostageGet import *
from PostagesGet import *
from PostageUpdate import *
from ProductAdd import *
from ProductGet import *
from ProductImgDelete import *
from ProductImgUpload import *
from ProductPropimgDelete import *
from ProductPropimgUpload import *
from ProductsGet import *
from ProductsSearch import *
from ProductUpdate import *
from PromotionActivityAdd import *
from PromotionActivityCancel import *
from PromotionActivityDelete import *
from PromotionActivityGet import *
from PromotionCouponAdd import *
from PromotionCoupondetailGet import *
from PromotionCouponSend import *
from PromotionCouponsGet import *
from PromotionMealAdd import *
from PromotionMealDelete import *
from PromotionMealGet import *
from PromotionMealUpdate import *
from PromotionMembersGet import *
from RefundGet import *
from RefundRefuse import *
from RefundsApplyGet import *
from RefundsReceiveGet import *
from SellercatsListAdd import *
from SellercatsListGet import *
from SellercatsListUpdate import *
from ShopcatsListGet import *
from ShopGet import *
from ShopRemainshowcaseGet import *
from ShopUpdate import *
from SkusCustomGet import *
from TaobaokeCaturlGet import *
from TaobaokeItemsConvert import *
from TaobaokeItemsDetailGet import *
from TaobaokeItemsGet import *
from TaobaokeListurlGet import *
from TaobaokeReportGet import *
from TaobaokeShopsConvert import *
from TaobaokeShopsGet import *
from TaobaokeToolRelation import *
from TaobaokeVirtualcardGet import *
from TaohuaBoughtitemIs import *
from TaohuaChildcatesGet import *
from TaohuaItemcommentAdd import *
from TaohuaItemcommentsGet import *
from TaohuaItemdetailGet import *
from TaohuaItemLike import *
from TaohuaItempayurlGet import *
from TaohuaItemresurlGet import *
from TaohuaItemsSearch import *
from TaohuaLatestupdateinfoGet import *
from TaohuaOrdersGet import *
from TaohuaPreviewurlGet import *
from TaohuaStaffrecitemsGet import *
from TimeGet import *
from TopApiruleSync import *
from TopatsDeliverySend import *
from TopatsResultGet import *
from TopatsTradeAccountreportGet import *
from TopatsTradesFullinfoGet import *
from TradeAmountGet import *
from TradeClose import *
from TradeConfirmfeeGet import *
from TradeFullinfoGet import *
from TradeGet import *
from TradeMemoAdd import *
from TradeMemoUpdate import *
from TradeOrderskuUpdate import *
from TraderateAdd import *
from TraderateListAdd import *
from TraderatesGet import *
from TradeReceivetimeDelay import *
from TradesBoughtGet import *
from TradeShippingaddressUpdate import *
from TradeSnapshotGet import *
from TradesSoldGet import *
from TradesSoldIncrementGet import *
from UserGet import *
from UsersGet import *
from VasOrderSearch import *
from VasSubscribeGet import *
from VasSubscSearch import *
from WangwangEserviceAvgwaittimeGet import *
from WangwangEserviceChatlogGet import *
from WangwangEserviceChatpeersGet import *
from WangwangEserviceChatrecordGet import *
from WangwangEserviceEvaluationGet import *
from WangwangEserviceGroupmemberGet import *
from WangwangEserviceNoreplynumGet import *
from WangwangEserviceOnlinetimeGet import *
from WangwangEserviceReceivenumGet import *
from WlbInventoryDetailGet import *
from WlbInventorylogQuery import *
from WlbInventorySync import *
from WlbItemAdd import *
from WlbItemAuthorizationAdd import *
from WlbItemAuthorizationDelete import *
from WlbItemAuthorizationQuery import *
from WlbItemCombinationCreate import *
from WlbItemCombinationDelete import *
from WlbItemCombinationGet import *
from WlbItemConsignmentCreate import *
from WlbItemConsignmentDelete import *
from WlbItemConsignmentPageGet import *
from WlbItemDelete import *
from WlbItemGet import *
from WlbItemMapGet import *
from WlbItemMapGetByExtentity import *
from WlbItemQuery import *
from WlbItemSynchronize import *
from WlbItemSynchronizeDelete import *
from WlbItemUpdate import *
from WlbNotifyMessageConfirm import *
from WlbNotifyMessagePageGet import *
from WlbOrderCancel import *
from WlbOrderConsign import *
from WlbOrderCreate import *
from WlbOrderitemPageGet import *
from WlbOrderPageGet import *
from WlbOrderScheduleRuleAdd import *
from WlbOrderscheduleruleDelete import *
from WlbOrderscheduleruleQuery import *
from WlbOrderScheduleRuleUpdate import *
from WlbOrderstatusGet import *
from WlbReplenishStatistics import *
from WlbSubscriptionQuery import *
from WlbTmsorderQuery import *
from WlbTradeorderGet import *
from WlbWlborderGet import *