application: tb-auto
version: 11-7
runtime: python
api_version: 1

builtins:

- datastore_admin: on

handlers:

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
  expiration : "30d"

- url: /static
  static_dir: static
  expiration: "30d"

- url: /cron.*
  script: cron.py
  login: admin

- url: /ajax.*
  script: ajax.py
  login: admin

- url: /onsale.*
  script: onsale.py
  login: admin

- url: /instock.*
  script: instock.py
  login: admin

- url: /trade.*
  script: trade.py
  login: admin

- url: /rate.*
  script: rate.py
  login: admin

- url: .*
  script: main.py
  login: admin